name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      # Указываем версию Node.js 20
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests
